//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace fbpm_cs.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class fbpmEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new fbpmEntities object using the connection string found in the 'fbpmEntities' section of the application configuration file.
        /// </summary>
        public fbpmEntities() : base("name=fbpmEntities", "fbpmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new fbpmEntities object.
        /// </summary>
        public fbpmEntities(string connectionString) : base(connectionString, "fbpmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new fbpmEntities object.
        /// </summary>
        public fbpmEntities(EntityConnection connection) : base(connection, "fbpmEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaymentSchedule> PaymentSchedules
        {
            get
            {
                if ((_PaymentSchedules == null))
                {
                    _PaymentSchedules = base.CreateObjectSet<PaymentSchedule>("PaymentSchedules");
                }
                return _PaymentSchedules;
            }
        }
        private ObjectSet<PaymentSchedule> _PaymentSchedules;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaymentSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaymentSchedules(PaymentSchedule paymentSchedule)
        {
            base.AddObject("PaymentSchedules", paymentSchedule);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PaymentScheduleModel", Name="PaymentSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaymentSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaymentSchedule object.
        /// </summary>
        /// <param name="scheduleID">Initial value of the ScheduleID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="scheduleDate">Initial value of the ScheduleDate property.</param>
        /// <param name="schedulePercent">Initial value of the SchedulePercent property.</param>
        /// <param name="bookedDate">Initial value of the BookedDate property.</param>
        /// <param name="bookingAmount">Initial value of the BookingAmount property.</param>
        /// <param name="scheduleAmount">Initial value of the ScheduleAmount property.</param>
        /// <param name="remainingAmount">Initial value of the RemainingAmount property.</param>
        public static PaymentSchedule CreatePaymentSchedule(global::System.Guid scheduleID, global::System.String userID, global::System.DateTime scheduleDate, global::System.Int32 schedulePercent, global::System.DateTime bookedDate, global::System.Decimal bookingAmount, global::System.Decimal scheduleAmount, global::System.Decimal remainingAmount)
        {
            PaymentSchedule paymentSchedule = new PaymentSchedule();
            paymentSchedule.ScheduleID = scheduleID;
            paymentSchedule.UserID = userID;
            paymentSchedule.ScheduleDate = scheduleDate;
            paymentSchedule.SchedulePercent = schedulePercent;
            paymentSchedule.BookedDate = bookedDate;
            paymentSchedule.BookingAmount = bookingAmount;
            paymentSchedule.ScheduleAmount = scheduleAmount;
            paymentSchedule.RemainingAmount = remainingAmount;
            return paymentSchedule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ScheduleID
        {
            get
            {
                return _ScheduleID;
            }
            set
            {
                if (_ScheduleID != value)
                {
                    OnScheduleIDChanging(value);
                    ReportPropertyChanging("ScheduleID");
                    _ScheduleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScheduleID");
                    OnScheduleIDChanged();
                }
            }
        }
        private global::System.Guid _ScheduleID;
        partial void OnScheduleIDChanging(global::System.Guid value);
        partial void OnScheduleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ScheduleText
        {
            get
            {
                return _ScheduleText;
            }
            set
            {
                OnScheduleTextChanging(value);
                ReportPropertyChanging("ScheduleText");
                _ScheduleText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ScheduleText");
                OnScheduleTextChanged();
            }
        }
        private global::System.String _ScheduleText;
        partial void OnScheduleTextChanging(global::System.String value);
        partial void OnScheduleTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ScheduleDate
        {
            get
            {
                return _ScheduleDate;
            }
            set
            {
                if (_ScheduleDate != value)
                {
                    OnScheduleDateChanging(value);
                    ReportPropertyChanging("ScheduleDate");
                    _ScheduleDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScheduleDate");
                    OnScheduleDateChanged();
                }
            }
        }
        private global::System.DateTime _ScheduleDate;
        partial void OnScheduleDateChanging(global::System.DateTime value);
        partial void OnScheduleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SchedulePercent
        {
            get
            {
                return _SchedulePercent;
            }
            set
            {
                if (_SchedulePercent != value)
                {
                    OnSchedulePercentChanging(value);
                    ReportPropertyChanging("SchedulePercent");
                    _SchedulePercent = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SchedulePercent");
                    OnSchedulePercentChanged();
                }
            }
        }
        private global::System.Int32 _SchedulePercent;
        partial void OnSchedulePercentChanging(global::System.Int32 value);
        partial void OnSchedulePercentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime BookedDate
        {
            get
            {
                return _BookedDate;
            }
            set
            {
                if (_BookedDate != value)
                {
                    OnBookedDateChanging(value);
                    ReportPropertyChanging("BookedDate");
                    _BookedDate = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookedDate");
                    OnBookedDateChanged();
                }
            }
        }
        private global::System.DateTime _BookedDate;
        partial void OnBookedDateChanging(global::System.DateTime value);
        partial void OnBookedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BookingAmount
        {
            get
            {
                return _BookingAmount;
            }
            set
            {
                if (_BookingAmount != value)
                {
                    OnBookingAmountChanging(value);
                    ReportPropertyChanging("BookingAmount");
                    _BookingAmount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BookingAmount");
                    OnBookingAmountChanged();
                }
            }
        }
        private global::System.Decimal _BookingAmount;
        partial void OnBookingAmountChanging(global::System.Decimal value);
        partial void OnBookingAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ScheduleAmount
        {
            get
            {
                return _ScheduleAmount;
            }
            set
            {
                if (_ScheduleAmount != value)
                {
                    OnScheduleAmountChanging(value);
                    ReportPropertyChanging("ScheduleAmount");
                    _ScheduleAmount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ScheduleAmount");
                    OnScheduleAmountChanged();
                }
            }
        }
        private global::System.Decimal _ScheduleAmount;
        partial void OnScheduleAmountChanging(global::System.Decimal value);
        partial void OnScheduleAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RemainingAmount
        {
            get
            {
                return _RemainingAmount;
            }
            set
            {
                if (_RemainingAmount != value)
                {
                    OnRemainingAmountChanging(value);
                    ReportPropertyChanging("RemainingAmount");
                    _RemainingAmount = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RemainingAmount");
                    OnRemainingAmountChanged();
                }
            }
        }
        private global::System.Decimal _RemainingAmount;
        partial void OnRemainingAmountChanging(global::System.Decimal value);
        partial void OnRemainingAmountChanged();

        #endregion

    
    }

    #endregion

    
}
