//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace fbpm_cs.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class fbpmSample : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new fbpmSample object using the connection string found in the 'fbpmSample' section of the application configuration file.
        /// </summary>
        public fbpmSample() : base("name=fbpmSample", "fbpmSample")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new fbpmSample object.
        /// </summary>
        public fbpmSample(string connectionString) : base(connectionString, "fbpmSample")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new fbpmSample object.
        /// </summary>
        public fbpmSample(EntityConnection connection) : base(connection, "fbpmSample")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sample> Samples
        {
            get
            {
                if ((_Samples == null))
                {
                    _Samples = base.CreateObjectSet<Sample>("Samples");
                }
                return _Samples;
            }
        }
        private ObjectSet<Sample> _Samples;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Samples EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSamples(Sample sample)
        {
            base.AddObject("Samples", sample);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleModel", Name="Sample")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sample : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sample object.
        /// </summary>
        /// <param name="sampleID">Initial value of the SampleID property.</param>
        public static Sample CreateSample(global::System.Guid sampleID)
        {
            Sample sample = new Sample();
            sample.SampleID = sampleID;
            return sample;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SampleID
        {
            get
            {
                return _SampleID;
            }
            set
            {
                if (_SampleID != value)
                {
                    OnSampleIDChanging(value);
                    ReportPropertyChanging("SampleID");
                    _SampleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SampleID");
                    OnSampleIDChanged();
                }
            }
        }
        private global::System.Guid _SampleID;
        partial void OnSampleIDChanging(global::System.Guid value);
        partial void OnSampleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SampleDesc
        {
            get
            {
                return _SampleDesc;
            }
            set
            {
                OnSampleDescChanging(value);
                ReportPropertyChanging("SampleDesc");
                _SampleDesc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SampleDesc");
                OnSampleDescChanged();
            }
        }
        private global::System.String _SampleDesc;
        partial void OnSampleDescChanging(global::System.String value);
        partial void OnSampleDescChanged();

        #endregion

    
    }

    #endregion

    
}
